### PR TITLE
Bump versions + Downstream HA-core suggestions

### PR DESCRIPTION
**Pull request by CoMPaTech**

### CODE REVIEW

**Comment by bouwew** [comment]
Oops, this will need a lot of ignoring :)
Better to ignore the whole file instead of single lines.

**Comment by CoMPaTech** [comment]
Yup, just wanted to see what it caused ... but we can, like core, ignore them. Just curious how far it got :P

**Comment by CoMPaTech** [comment]
[5baa0c3](https://github.com/plugwise/python-plugwise/pull/174/commits/5baa0c3f120dc6e596fd4de217655824112b6dbf) - [f1fe346](https://github.com/plugwise/python-plugwise/pull/174/commits/f1fe346fb1fcb881d5b9a4782ffa66db4ccd87f1) just to make sure testing etc. still worked, reverted to `helper` and `smile` for typing progress

**Comment by CoMPaTech** [comment]
Very nice! 🥳

**Pull request merged**
