### PR TITLE
Pyproject.toml PEP-621 including versioning & cleanup of separate config files

### PR DESCRIPTION
**Pull request by CoMPaTech**
- Set default version to 3.10 (keeping 3.9)
- Merge various files into pyproject.toml (flake8, coveragerc, (most of) setup.cfg, pytest.ini)
- Adjust versioning approach (setup.py -> plugwise/__init__.py) accordingly
- Bump pre-commit updates (dependanbot still can't do that) keeping flake8 at v4 (version compat with HA-core)
- Actually use what we define in our project setup (to be pyproject.yaml) for installing requirements :)
-

### CODE REVIEW

**Review by bouwew — APPROVED** [review]
LGTM!

**Comment by CoMPaTech** [comment]
> LGTM!

0.28.0a1 acceptable for a next commit (involving merging of most things into pyproject)?

**Comment by CoMPaTech** [comment]
Looks ok now and uses proper version from pyproject

**Comment by CoMPaTech** [comment]
Good call(s) ... for now it was just merging, we should look again and check if we have all/need all (mostly towards the flake8 things)

**Comment by CoMPaTech** [comment]
Hmmm, didn't intend on pre-commit ci to end up here, let's do #255 first

**Comment by CoMPaTech** [comment]
pre-commit.ci run

**Pull request merged**
