### PR TITLE
Test

### PR DESCRIPTION
**Pull request by CoMPaTech**
Fix `async_timeout` testability (i.e. phased it out) and rely on `aiohttp`. Make dependencies more in line with HA instead of noting them down ourselves.

I.e. we can still override in `setup.py` (which PyPi/pip use) and where required override ourselves using `package_constraints.txt`. Requires recent enough pip.

### CODE REVIEW

**Review by bouwew — COMMENTED** [review]
Remove the `except pw_exceptions.DeviceTimeoutError` lines?
To keep the 100% testcoverage.

**Comment by bouwew** [comment]
Looking good, nice work!
Maybe remove the debug messages?

**Comment by CoMPaTech** [comment]
Removed debug, increased cache to ensure proper working

**Review by bouwew — APPROVED** [review]
LGTM!

**Pull request merged**
