### PR TITLE
Install pre-commit.ci

### PR DESCRIPTION
**Pull request by CoMPaTech**
Add pre-commit checking/updating (as dependabot doesn't support that)

### CODE REVIEW

**Comment by CoMPaTech** [comment]
pre-commit.ci run

**Comment by CoMPaTech** [comment]
pre-commit.ci run

**Comment by CoMPaTech** [comment]
pre-commit.ci run

**Comment by CoMPaTech** [comment]
Hmmm, need to figure out how to get pylint back :)

**Comment by CoMPaTech** [comment]
pre-commit.ci run

**Comment by CoMPaTech** [comment]
pre-commit.ci run

**Comment by CoMPaTech** [comment]
> Hmmm, need to figure out how to get pylint back :)

PyCQA themselves skip as well, so let's just keep pylint in verify-actions

**Comment by CoMPaTech** [comment]
pre-commit.ci run

**Review by bouwew — APPROVED** [review]
LGTM!

**Comment by CoMPaTech** [comment]
👍

**Pull request merged**
