### PR TITLE
WIP: Prepare Python 3.11

### PR DESCRIPTION
**Pull request by CoMPaTech**
Blocked until HA-core/package_constraints.txt is bumped to aiohttp>3.8.1

### CODE REVIEW

**Comment by frenck** [comment]
> Blocked until HA-core/package_constraints.txt is bumped to aiohttp-3.8.3

That won't happen `aiohttp` 3.8.3 has a serious memory leak, we have reverted that upgrade and are awaiting upstream. One thing is for sure, it will never ben 3.8.3 again :)

**Comment by CoMPaTech** [comment]
Noted, thanks for the explanation - waiting for upstream bump of aiohttp above 3.8.1 - adjusted the initial comment to say > 3.8.1 :)

**Comment by CoMPaTech** [comment]
@brefra (or @bouwew) could you look at `plugwise/connections/socket.py` I think pylint is rightfully stating the no-raise-else and it suggest to just de-indent (which I now did)

@bouwew why did we have HomeAssistantError in pyproject (otherwise we'll need to re-add it prepended by the module, just like with the built-ins)

**Comment by CoMPaTech** [comment]
For record keeping, following up with aiohttp 3.8.4 as now in core (though core is also still waiting for 3.9 release)

**Comment by bouwew** [comment]
@CoMPaTech, HomeAssistantError, must be a left-over or a mistake.
Not used anywhere.

**Review by bouwew — APPROVED** [review]
LGTM!

**Comment by CoMPaTech** [comment]
As discussed on the side, not defaulting to 3.11 yet

**Pull request merged**
