### PR TITLE
QA: Improve code - reintroduce flake/lint

### PR DESCRIPTION
**Pull request by CoMPaTech**
Whenever #123 is merged it will be clear why we need this, marked it as QA but there are quiet a few catches by lint.

#123 and next #127 are of (way!) more priority than this PR, Opening PRs to keep track of all active (related) branches

### CODE REVIEW

**Comment by CoMPaTech** [comment]
@brefra please doublecheck my changes on the USB code (suggestions/improvements welcome)

@bouwew walrus marked as a clear TODO

**Review by bouwew — APPROVED** [review]
W.r.t. the Smile-parts of the code, looking good to me.

**Comment by CoMPaTech** [comment]
Closese #26 (at least partially)

**Comment by CoMPaTech** [comment]
Closes #26 (at least partially)

**Comment by CoMPaTech** [comment]
Closes #113

**Pull request merged**
