### PR TITLE
Remove workarounds (HA-core updated to aiohttp 3.10.1

### PR DESCRIPTION
**Pull request by CoMPaTech**
## Summary by CodeRabbit

- **Chores**
	- Streamlined the changelog by removing the "ongoing" section for clearer version-specific updates.
	- Simplified the testing script by removing outdated code related to the `aiohttp` library, improving maintainability.

### CODE REVIEW

**Comment by CoMPaTech** [comment]
Fixes #600 596

**Comment by CoMPaTech** [comment]
Fixes #596

**Review by bouwew — COMMENTED** [review]
Should we remove the patch-dir/-file too?

**Comment by CoMPaTech** [comment]
> Should we remove the patch-dir/-file too?

Oops :)

**Review by bouwew — APPROVED** [review]

**Pull request merged**
