### PR TITLE
Improve code styling-quality and migrate to GitHub actions

### PR DESCRIPTION
**Pull request by CoMPaTech**
Codespell fixes
Flake8 improvements
 - [x] Some todo's on complexity => todo for #28
 - [x] Lots of `== True`, `== False` and `!= None` corrected (but they should be evaluated to be 'if cond:' instead of 'if cond is True' probably => todo for  #27 
 - [x] Make github actions validate commits (like pre-commit already does, but force it)
 - [x] Make github action test the code and do codecov
 - [x] Switch from Travis doing pypi and testing to Github Actions

~~Added Github actions to replace Travis - I did not include ad Github action for the PyPi publishing yet, first build some experience with github actions (it does do codecov though, so we'll have to take that out of travis eventually).~~

Travis is switching everything from .org to .com [check this](https://docs.travis-ci.com/user/migrate/open-source-repository-migration#frequently-asked-questions) and having everything in github seems doable.

If we merge this we switch to Github actions and travis is being disabled (for now). See the 'Checks' tab at the top for everything that happens!

### CODE REVIEW

**Comment by CoMPaTech** [comment]
Works (https://test.pypi.org/project/plugwise/#history) => 0.8.2a0

**Comment by bouwew** [comment]
Yes correct, `if x is True` should become `if x`, `if x is False` should become `if not x`.

And to be honest, there must be bugs in black. Look at const.py, at my latest attempt it made all SMILES-entries 1-liners, now it is changed back to multi-liner except for the last 2 ?!

**Comment by CoMPaTech** [comment]
Yeah, that was on my list of things, also isort is acting weird or something else is acting up on plugwise/parser.py

**Comment by bouwew** [comment]
I see `print()` commands in several places in the stick-code, should we replace these by `_LOGGER.debug()` commands?

**Comment by CoMPaTech** [comment]
> I see `print()` commands in several places in the stick-code, should we replace these by `_LOGGER.debug()` commands?

```
                  if self.print_progress:
                      print("Scan Plugwise network")
                  self.scan(callback)
```

Apparently they are part of of the `self.print_progress` variable of the `stick` class. I guess they should be debug indeed. @brefra?

**Comment by bouwew** [comment]
And we should replace all `_LOGGER_debug("... %s ...", var), _LOGGER_debug("... %s ... %s ...", (var1, var2))` by `_LOGGER_debug(f"... {var } ..."),  LOGGER_debug(f"... {var1}... {var2} ...")`

**Comment by CoMPaTech** [comment]
> And we should replace all `_LOGGER_debug("... %s ...", var), _LOGGER_debug("... %s ... %s ...", (var1, var2))` by `_LOGGER_debug(f"... {var} ..."), LOGGER_debug(f"... {var1}... {var2} ...")`

Good call, but maybe we should have a look at the vast amount of them and if we can't make that smarter
```
# _LOGGER.debug statements
  10 node.py
  14 parser.py
   3 smile.py
  47 stick.py
```

Constructions like
```
                            _LOGGER.info(
                                "Resend %s for %s because stick did not acknowledge request (%s), last seq_id=%s",
                                str(
                                    self.expected_responses[seq_id][
                                        1
                                    ].__class__.__name__
                                ),
                                mac,
                                str(seq_id),
                                str(self.last_ack_seq_id),
                            )
```
won't make it more readable (pointing at the str self expected response part). And I see some of them even with calculations in those fields

**Comment by bouwew** [comment]
Smarter and/or less debugging? But that is mostly for @brefra to judge.

**Comment by CoMPaTech** [comment]
Created 3 `[IMPROVE]` issues for the separate improvements, also renamed this PR to clarify it's about code styling quality and github actions, aiming to keep (this) PR(s) as small as possible.

**Comment by CoMPaTech** [comment]
Latest commit adds code security scanning as per https://github.com/plugwise/python-plugwise/security/code-scanning

**Review by bouwew — COMMENTED** [review]
My suggestions:
- change all `if something is True:` to `if something:`
- change all `if something is False:` to `if not something:`

What about removing the `crc = response[:4]`, @brefa, is that OK?

**Comment by CoMPaTech** [comment]
We can, but let's do that in #30 then (crc is already checked off in that one)

**Review by bouwew — APPROVED** [review]
I'm thinking out loud here: what's the difference between #24 and #30? Very difficult to judge with all the many changes :)

Any, please go ahead, I'll review again when #30 is ready for review, after #24 has been merged.

**Comment by CoMPaTech** [comment]
> I'm thinking out loud here: what's the difference between #24 and #30? Very difficult to judge with all the many changes :)
> 
> Any, please go ahead, I'll review again when #30 is ready for review, after #24 has been merged.

Hence the heads-up in discord that #30 was build upon #24 ... so to first get #24 out of the way.

**Pull request merged**
