### PR TITLE
Small testing improvements

### PR DESCRIPTION
**Pull request by CoMPaTech**
Small improvements ... wondering if the `with async_io timeout` in `request` ever would reach it's exception, needs more inspection. (It seems that the intended timeouts from the testing class only get `ResponseError` back and no raise of `aiohttp.timeouterror`. That (now missing coverage) exception should be tested. Also the websession structure needs improvement in module and accompanying tests later on.

Fixed some small pylint things, bluntly test missing websession and added the `delete_notification` test.

### CODE REVIEW

**Review by bouwew — APPROVED** [review]
Looking good!

**Comment by CoMPaTech** [comment]
After some thorough testing ... lets evaluate if we come to the same conclusion, it is based on not being able to 'let it fail' on appliances (didn't test with modules to be honest). Testing with locations or domain_objects won't work since these are part of connect (and as such the device would fail much earlier on having wrong information than in the update-loop).

https://github.com/plugwise/python-plugwise/blob/6f3a56fa31d762e6b802428d121048ff0eb01741/plugwise/smile.py#L258-L268

Prevent any mishaps in either `empty` responses or invalid XML, therefore we should be able to clean-up the helper functions (apart from the domain_objects-one because of notifications) and most of `full_update_device` to merely something like:

```
      async def update_domain_objects(self):
          """Request domain_objects data."""
          self._domain_objects = await self.request(DOMAIN_OBJECTS)

          # If Plugwise notifications present:
          self.notifications = {}
          notifications = self._domain_objects.findall(".//notification")
          for notification in notifications:
              try:
                  msg_id = notification.attrib["id"]
                  msg_type = notification.find("type").text
                  msg = notification.find("message").text
                  self.notifications.update({msg_id: {msg_type: msg}})
                  _LOGGER.debug("Plugwise notifications: %s", self.notifications)
              except AttributeError:  # pragma: no cover
                  url = f"{self._endpoint}{DOMAIN_OBJECTS}"
                  _LOGGER.info(
                      "Plugwise notification present but unable to process, manually investigate: %s",
                      url,
                  )

      async def full_update_device(self):
          """Update all XML data from device."""
          await self.update_domain_objects()
          await self._locations = self.request(LOCATIONS)

          # P1 legacy has no appliances
          if not (self.smile_type == "power" and self._smile_legacy):
              await self._appliances = self.request(APPLIANCES)

          # Stretch_v2 only uses modules
          if self.smile_type == "stretch" and self.smile_version[1].major == 2:
              await self._modules = self.request(MODULES)
```

I tested by feeding in 'empty returns' (caught by `request` first lines as quoted), faulty XML (second part of the quote) and correct but only the appliances part. It looks like feeding wrong information won't work.

**Comment by CoMPaTech** [comment]
Marking ready for review ... last (big comment) should be evaluated as issue, creating accordingly

**Review by bouwew — APPROVED** [review]
Looking good!

**Comment by bouwew** [comment]
And good suggestions w.r.t. the code, these changes have been among others, implemented (and tested) in the branch `optimize`.

**Comment by CoMPaTech** [comment]
Skipping version bump in favour of @bouwew's upcoming PR

**Pull request merged**
