### PR TITLE
Fix bug for battery powered devices & attempt to fix memory leak

### PR DESCRIPTION
**Pull request by brefra**
Fix potential crash of submit thread when queued message of SED (battery powered devices) are send.
Attempt to fix memory leak reported at https://github.com/plugwise/plugwise-beta/issues/312 by introducing thread locking.

My setup, running this change, is stable for two day's now so looks promising....

### CODE REVIEW

**Review by bouwew — APPROVED** [review]
Looking good to me!

Please raise the version to v0.27.7 both in the files CHANGELOG.md and pyproject.toml

**Comment by bouwew** [comment]
I'll create a plugwise-beta test-release first.

**Comment by bouwew** [comment]
Memory leak doesn't look to be fixed: https://community.home-assistant.io/t/plugwise-core-and-custom-component/236250/323

**Comment by bouwew** [comment]
@brefra are there any more changes coming? If not, should we merge and release this update?

**Comment by bouwew** [comment]
Let's release to get this improvement out to more users.

**Comment by CoMPaTech** [comment]
See https://github.com/plugwise/python-plugwise/blob/28e2aaa4b86d6e26bb8deeb68153deff0789783f/pyproject.toml#L170

**Comment by CoMPaTech** [comment]
🥳

**Pull request merged**
