### PR TITLE
Follow beta/core with uv

### PR DESCRIPTION
**Pull request by CoMPaTech**
## Summary by CodeRabbit

- **New Features**
	- Introduced a new dependency to enhance the testing environment for better handling of asynchronous programming or web requests.
	- Updated the installation process to prioritize the new dependency, ensuring proper setup for testing scripts.

- **Bug Fixes**
	- Adjusted the GitHub Actions workflow to improve code quality checks by switching to a non-modifying check mode for the `ruff` tool.
	- Enhanced the handling of specific package versions during testing with a new patching approach.

- **Documentation**
	- Modified the instructions in the test initialization documentation to reflect the new installation command.
	- Added a section in the changelog to clarify ongoing development tasks related to dependency management.

### CODE REVIEW

**Review by bouwew — APPROVED** [review]
LGTM!

**Comment by CoMPaTech** [comment]
Quickly mocked our 404-path handling in https://gist.github.com/CoMPaTech/541eb68906431933d2b3ea48e886b92b failing on aiohttp 3.10.0 and working on 3.9.5 and lower.

Link https://github.com/aio-libs/aiohttp/issues/8567

**Comment by CoMPaTech** [comment]
Set to draft pending outcome

**Comment by CoMPaTech** [comment]
@coderabbitai review

**Comment by CoMPaTech** [comment]
@bouwew apparently ruff was also mixed in somewhere (+additional `uv` parts missing in GitHub workflow), added as such

**Review by bouwew — APPROVED** [review]

**Pull request merged**
