### PR TITLE
Add Anna (without boiler) fw4.41 data

### PR DESCRIPTION
**Pull request by CoMPaTech**
Todo:
 - [x] Migrate/fix adam_jip
 - [x] Cleanup older v4 tests / migrate to 4.4
 - [ ] Cleanup old firmware from fixtures (i.e. userdata/archive, tests/test_smile.py)
   - [x]  p1v3 Cleaned
   - [x]  anna_without_boiler Cleaned
   - [ ] others?

### CODE REVIEW

**Comment by CoMPaTech** [comment]
The modified `adam_jip` is now generated according to the others, e.g. becoming `m_adam_jip`. Purged first batch of older firmwares as discussed. Addition of the 'fixture generation only' is non-intrusive (used it to speed up validating fixtures without performing all device tests).

**Review by bouwew — APPROVED** [review]
LGTM

**Comment by bouwew** [comment]
@CoMPaTech please have a final look at the stuff I've added.

**Comment by CoMPaTech** [comment]
LGTM - do we need anything else (feel free to merge otherwise)

**Pull request merged**
