### PR TITLE
Split testing - initial split

### PR DESCRIPTION
**Pull request by CoMPaTech**
Split testing into separate files (improving maintenance & less lengthy monolith file) als dropping 'smile' as that's default for this repo

### CODE REVIEW

**Comment by CoMPaTech** [comment]
Adding quality label as per second half of the commits regarding the SonarCloud smells

**Comment by CoMPaTech** [comment]
Not sure why the pragma disable (complexity) won't apply (search for `disable` and `restore` with `S3776`). As for the final one on one function always returning true, that does raise an eyebrow.

**Review by bouwew — APPROVED** [review]
Look good!

**Comment by CoMPaTech** [comment]
Anything else we need to do here, or merge it and see what #485 can bring to the table?

**Comment by CoMPaTech** [comment]
(and apologies for not correctly saving the transfer of combined :) )

**Comment by bouwew** [comment]
No, all looks good now, please merge.

**Pull request merged**
